In [32]:
import pandas as pd
import re

In [33]:
df = pd.read_csv("puzzle3.txt", header=None, sep=": ")
df.columns = ["game", "sequence"]
df

/var/folders/pm/vw9pw9_93bl47zh9mtqphvb00000gn/T/ipykernel_32152/3970191632.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df = pd.read_csv("puzzle3.txt", header=None, sep=": ")

        game                                           sequence
0     Game 1  7 blue, 5 red; 10 red, 7 blue; 5 blue, 4 green...
1     Game 2  8 green, 3 red; 7 blue, 6 red, 8 green; 7 blue...
2     Game 3  6 blue, 3 red, 7 green; 3 red, 3 green, 8 blue...
3     Game 4  3 red, 4 green; 5 red, 1 blue; 2 green; 3 gree...
4     Game 5  17 red, 5 blue, 3 green; 8 green, 9 red, 10 bl...
..       ...                                                ...
95   Game 96  4 red, 4 blue, 4 green; 5 blue, 5 green, 4 red...
96   Game 97  6 red, 13 green, 3 blue; 10 green, 4 blue; 3 r...
97   Game 98  8 red, 12 green, 2 blue; 7 green, 8 red, 1 blu...
98   Game 99  6 blue, 11 red, 7 green; 9 red, 6 green, 1 blu...
99  Game 100  1 red, 4 blue, 2 green; 6 red, 2 green, 11 blu...

[100 rows x 2 columns]

In [34]:
df["game_id"] = df.game.str.split(" ").str[-1].astype("int32")
df

        game                                           sequence  game_id
0     Game 1  7 blue, 5 red; 10 red, 7 blue; 5 blue, 4 green...        1
1     Game 2  8 green, 3 red; 7 blue, 6 red, 8 green; 7 blue...        2
2     Game 3  6 blue, 3 red, 7 green; 3 red, 3 green, 8 blue...        3
3     Game 4  3 red, 4 green; 5 red, 1 blue; 2 green; 3 gree...        4
4     Game 5  17 red, 5 blue, 3 green; 8 green, 9 red, 10 bl...        5
..       ...                                                ...      ...
95   Game 96  4 red, 4 blue, 4 green; 5 blue, 5 green, 4 red...       96
96   Game 97  6 red, 13 green, 3 blue; 10 green, 4 blue; 3 r...       97
97   Game 98  8 red, 12 green, 2 blue; 7 green, 8 red, 1 blu...       98
98   Game 99  6 blue, 11 red, 7 green; 9 red, 6 green, 1 blu...       99
99  Game 100  1 red, 4 blue, 2 green; 6 red, 2 green, 11 blu...      100

[100 rows x 3 columns]

In [35]:
def parse_sequence(sequence):
    shown_hands = sequence.replace("; ", ",").replace(", ", ",").split(",")
    values = {
        "red": [],
        "blue": [],
        "green": []
    }
    for hand in shown_hands:
        #print(hand)
        amount, color = hand.split(" ")
        amount = int(amount)
        values[color].append(amount)
    return values

In [36]:
parse_sequence("3 red, 4 green; 5 red, 1 blue; 2 green")

{'red': [3, 5], 'blue': [1], 'green': [4, 2]}

In [49]:
def is_sequence_possible(sequence):
    try:
        values = parse_sequence(sequence)
    except:
        print(sequence)
    red_max = max(values["red"])
    blue_max = max(values["blue"])
    green_max = max(values["green"])
    #  12 red cubes, 13 green cubes, and 14 blue cubes
    return red_max <= 12 and green_max <= 13 and blue_max <= 14

In [50]:
is_sequence_possible("3 red, 4 green; 5 red, 1 blue; 2 green")

True

In [51]:
is_sequence_possible("3 red, 4 green; 53 red, 1 blue; 2 green")

False

In [52]:
is_sequence_possible("7 blue, 5 red; 10 red, 7 blue; 5 blue, 4 green, 15 red; 4 green, 6 red, 7 blue; 5 green, 8 blue, 4 red; 5 red, 4 blue, 3 green")

False

In [53]:
df["possible_sequence"] = df.sequence.apply(is_sequence_possible)

In [54]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
pd.set_option('max_colwidth', -1)

/var/folders/pm/vw9pw9_93bl47zh9mtqphvb00000gn/T/ipykernel_32152/3854843488.py:4: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option('max_colwidth', -1)

In [55]:
df

        game                                                                                                                                                sequence  game_id  possible_sequence
0   Game 1    7 blue, 5 red; 10 red, 7 blue; 5 blue, 4 green, 15 red; 4 green, 6 red, 7 blue; 5 green, 8 blue, 4 red; 5 red, 4 blue, 3 green                          1        False
1   Game 2    8 green, 3 red; 7 blue, 6 red, 8 green; 7 blue, 3 green, 6 red; 8 green, 6 blue, 11 red; 6 blue, 3 green, 12 red                                        2        True
2   Game 3    6 blue, 3 red, 7 green; 3 red, 3 green, 8 blue; 8 blue, 11 red, 4 green; 5 blue, 7 red, 6 green; 9 blue, 7 green, 1 red                                 3        True
3   Game 4    3 red, 4 green; 5 red, 1 blue; 2 green; 3 green, 1 blue; 2 green, 1 blue, 1 red                                                                         4        True
4   Game 5    17 red, 5 blue, 3 green; 8 green, 9 red, 10 blue; 2 green, 9 blue, 4 red                                                                                5        False
5   Game 6    5 blue, 6 green, 3 red; 1 green, 8 blue, 12 red; 2 blue, 13 red, 6 green                                                                                6        False
6   Game 7    1 green, 1 blue, 6 red; 1 red, 8 green; 3 red, 8 green, 2 blue; 14 green, 4 blue, 4 red; 4 green, 5 blue; 7 green, 2 blue, 1 red                        7        False
7   Game 8    6 blue, 9 red, 3 green; 2 red, 6 blue; 2 green, 1 red, 2 blue; 2 green, 9 blue, 6 red                                                                   8        True
8   Game 9    5 green, 8 blue, 8 red; 2 blue, 6 green, 8 red; 6 red, 9 green                                                                                          9        True
9   Game 10   2 red, 2 blue, 12 green; 8 green, 3 red; 5 blue, 11 red, 6 green; 14 red, 1 green                                                                       10       False
10  Game 11   2 green, 1 red, 1 blue; 4 blue, 7 red; 7 red, 7 green, 5 blue; 2 blue, 3 red, 6 green; 3 blue, 9 red, 7 green                                           11       True
11  Game 12   9 green, 7 red, 7 blue; 6 green, 4 blue, 1 red; 3 blue, 5 red, 7 green; 9 green, 10 red, 12 blue; 11 green, 5 red; 9 blue, 12 green, 3 red              12       True
12  Game 13   7 blue, 7 red, 2 green; 5 blue, 5 green, 7 red; 1 blue, 10 red; 11 red, 2 blue, 1 green; 1 green, 1 blue, 4 red                                         13       True
13  Game 14   2 blue, 10 red; 3 blue, 6 green, 17 red; 3 green, 4 blue, 14 red                                                                                        14       False
14  Game 15   7 blue, 2 green, 4 red; 7 blue, 3 red, 3 green; 4 red, 2 green, 1 blue; 2 red, 9 green, 5 blue; 2 red, 4 green, 5 blue                                  15       True
15  Game 16   5 blue, 1 red; 8 blue, 1 green; 5 green, 3 blue, 2 red; 8 blue, 2 green; 2 red, 2 blue, 5 green                                                         16       True
16  Game 17   2 blue, 5 red; 7 red, 1 blue; 2 blue, 2 green, 3 red; 3 blue, 2 red, 1 green; 5 green, 7 red; 6 red, 3 green                                            17       True
17  Game 18   4 blue, 1 red, 14 green; 8 red, 4 blue, 14 green; 6 red, 11 blue, 10 green; 5 blue, 2 green, 3 red; 16 green, 10 blue, 2 red; 6 red, 4 blue, 12 green   18       False
18  Game 19   10 green, 12 red, 12 blue; 5 blue, 12 red, 7 green; 15 red, 8 blue, 6 green; 13 green, 1 red, 10 blue; 4 blue, 8 red, 9 green; 16 red, 7 green, 3 blue  19       False
19  Game 20   10 blue, 9 green; 9 blue, 1 red, 3 green; 11 blue; 6 blue; 8 blue, 10 green                                                                             20       True
20  Game 21   4 blue, 4 red; 1 green, 3 red, 3 blue; 4 blue, 1 green, 2 red                                                                                           21       True
21  Game 22   5 blue, 4 green, 1 red; 14 green, 4 blue, 1 red; 4 blue, 4 red, 13 green                                                                                22       False
22  Game 23   6 red, 8 green; 4 green, 1 blue, 7 red; 10 green, 5 red; 2 red, 9 green                                                                                 23       True
23  Game 24   1 blue, 10 green; 12 green, 5 blue; 1 red, 3 green; 2 red, 4 blue                                                                                       24       True
24  Game 25   2 blue, 3 red, 13 green; 7 blue, 15 green, 1 red; 7 blue, 2 green                                                                                       25       False
25  Game 26   20 red, 5 blue, 4 green; 1 green, 8 blue, 11 red; 7 blue, 6 red, 2 green; 4 green, 7 blue, 4 red; 5 red, 8 blue                                         26       False
26  Game 27   3 red, 3 green, 1 blue; 3 red, 1 blue, 8 green; 3 blue, 4 red                                                                                           27       True
27  Game 28   1 blue, 15 red, 2 green; 15 red; 3 red, 2 green; 3 red, 1 green                                                                                         28       False
28  Game 29   4 blue, 7 green, 1 red; 5 green, 9 red; 8 green, 1 red, 10 blue; 2 blue, 1 green                                                                        29       True
29  Game 30   9 blue, 5 red, 6 green; 15 red, 6 blue, 3 green; 13 red, 2 blue, 4 green; 2 green, 3 blue; 13 red, 8 blue; 5 green, 6 blue, 17 red                      30       False
30  Game 31   1 green, 9 blue, 9 red; 4 green, 8 red, 1 blue; 10 blue, 2 green; 1 red, 1 blue; 1 red, 1 blue; 6 blue, 9 red, 5 green                                  31       True
31  Game 32   7 red, 7 green, 3 blue; 14 green, 11 red, 11 blue; 10 green, 7 red, 2 blue; 1 green, 4 blue, 4 red; 9 blue, 10 green, 5 red                             32       False
32  Game 33   12 red, 4 green, 11 blue; 4 blue, 10 red, 1 green; 7 green, 10 red, 16 blue; 15 red, 5 blue; 10 green, 4 red; 8 green, 5 blue, 6 red                    33       False
33  Game 34   8 blue, 1 red, 2 green; 3 green, 3 blue, 4 red; 6 red, 3 green; 6 red; 9 blue, 4 red, 3 green                                                           34       True
34  Game 35   6 green, 6 blue, 1 red; 3 green, 3 blue; 1 red, 5 blue, 2 green; 1 red, 13 green, 1 blue; 3 green, 1 red, 10 blue; 5 green, 4 blue                      35       True
35  Game 36   15 blue, 1 red; 2 red, 3 green, 17 blue; 6 blue, 7 red, 8 green; 12 red, 7 green, 14 blue; 4 blue, 2 red; 8 green, 12 blue, 10 red                      36       False
36  Game 37   2 green, 2 blue; 6 red, 3 blue, 1 green; 2 green, 3 blue, 1 red                                                                                         37       True
37  Game 38   2 blue, 7 red, 9 green; 3 red, 18 green, 6 blue; 6 red, 19 green, 2 blue; 2 blue, 13 green, 7 red                                                       38       False
38  Game 39   12 blue, 7 green, 3 red; 16 green, 6 blue; 1 red, 4 green, 2 blue; 15 blue, 2 red, 2 green                                                              39       False
39  Game 40   18 blue, 1 red; 4 green, 15 blue; 5 green, 17 blue, 3 red; 4 red, 16 blue, 2 green                                                                      40       False
40  Game 41   3 blue, 14 green; 11 green, 8 blue; 14 blue, 4 red, 1 green; 5 blue, 2 red, 15 green                                                                    41       False
41  Game 42   7 red, 9 green; 10 red, 19 green, 10 blue; 16 blue, 8 green, 7 red; 6 blue, 11 green, 7 red                                                             42       False
42  Game 43   1 blue, 5 red; 8 red, 2 green, 1 blue; 4 red, 3 green; 2 green, 1 red                                                                                   43       True
43  Game 44   5 green, 13 blue, 12 red; 18 blue, 3 green, 8 red; 2 green, 3 blue, 11 red                                                                              44       False
44  Game 45   3 blue, 1 red, 4 green; 2 blue, 1 red; 1 blue, 4 green; 3 red, 16 green                                                                                 45       False
45  Game 46   10 red, 1 green, 4 blue; 4 green, 14 blue, 2 red; 12 red, 3 blue, 2 green; 4 green, 2 red, 2 blue; 2 red, 1 green, 11 blue; 2 green, 19 blue            46       False
46  Game 47   10 blue, 10 green, 3 red; 3 red, 11 blue, 9 green; 4 blue, 10 green                                                                                     47       True
47  Game 48   5 green, 1 blue; 4 red, 8 green, 8 blue; 17 red, 5 blue, 2 green; 12 green, 18 red, 7 blue; 15 green, 14 red, 8 blue; 11 green, 1 blue, 16 red          48       False
48  Game 49   2 red, 4 green, 1 blue; 1 green, 5 blue, 2 red; 8 green, 3 blue, 1 red; 4 blue, 3 red, 9 green                                                          49       True
49  Game 50   2 blue; 7 green, 5 red; 3 red, 3 blue; 5 green, 1 blue, 2 red; 5 blue, 3 green; 4 green, 3 blue, 1 red                                                  50       True
50  Game 51   6 green, 13 blue, 3 red; 7 blue, 7 green, 1 red; 15 green, 2 red, 13 blue; 1 red, 7 blue, 3 green; 11 blue, 16 green, 1 red                             51       False
51  Game 52   5 blue, 2 green, 14 red; 4 blue, 3 red; 10 green, 7 red; 1 blue, 10 green, 10 red; 9 blue, 5 green, 12 red                                              52       False
52  Game 53   1 green, 2 red, 1 blue; 4 green; 1 green; 2 green; 2 green, 1 red                                                                                       53       True
53  Game 54   3 green, 11 blue; 12 blue; 1 red, 3 blue; 7 blue, 1 red                                                                                                 54       True
54  Game 55   7 green, 7 red; 1 blue, 7 green, 14 red; 17 red, 2 blue, 5 green; 1 blue, 7 red; 2 blue, 3 green, 14 red                                                55       False
55  Game 56   3 blue, 2 red, 1 green; 1 red, 4 blue, 2 green; 5 green, 1 red, 2 blue; 7 blue                                                                          56       True
56  Game 57   1 blue, 14 red, 7 green; 2 red, 1 green; 1 blue, 6 red, 6 green                                                                                         57       False
57  Game 58   11 red, 2 green; 3 green, 8 red, 8 blue; 10 red, 1 green, 13 blue                                                                                       58       True
58  Game 59   11 green, 5 blue, 11 red; 13 red, 6 blue, 11 green; 6 red, 7 blue, 12 green; 9 blue, 9 red, 1 green                                                     59       False
59  Game 60   3 red, 8 blue, 4 green; 5 blue, 2 red, 3 green; 7 green, 3 red; 8 blue, 2 red, 7 green                                                                  60       True
60  Game 61   17 red, 12 blue, 9 green; 20 green, 5 red, 14 blue; 9 blue, 11 green, 15 red; 14 green, 6 blue, 14 red; 16 green, 7 red, 4 blue                         61       False
61  Game 62   3 red, 11 blue, 16 green; 1 green, 6 red, 6 blue; 7 green, 6 red, 9 blue                                                                                62       False
62  Game 63   3 blue, 20 red, 1 green; 11 red, 5 green; 13 red, 2 green; 15 red, 1 blue, 6 green                                                                      63       False
63  Game 64   8 blue, 1 red, 11 green; 1 red, 11 blue, 4 green; 5 red, 7 green, 1 blue                                                                                64       True
64  Game 65   3 blue, 13 green, 2 red; 2 blue, 3 red; 10 green, 8 blue, 2 red; 2 red, 6 blue, 8 green; 10 blue, 12 green                                              65       True
65  Game 66   4 blue, 3 red, 8 green; 1 red, 9 green; 7 blue, 6 red, 6 green; 1 blue, 1 red, 11 green                                                                 66       True
66  Game 67   10 blue, 15 green; 3 red, 2 blue, 1 green; 4 blue, 12 green, 2 red; 8 green, 11 blue, 8 red; 9 blue, 5 green, 6 red; 10 green, 4 red, 14 blue           67       False
67  Game 68   4 green, 3 blue, 4 red; 9 green, 2 blue; 6 blue, 6 red, 10 green; 5 blue, 4 green, 5 red; 3 blue, 10 green; 5 blue, 5 red                               68       True
68  Game 69   6 blue, 1 red, 1 green; 4 red, 3 green, 2 blue; 5 green, 3 red, 5 blue; 5 red, 5 blue                                                                   69       True
69  Game 70   2 green, 1 red; 12 green, 1 red, 11 blue; 7 green, 12 blue; 13 blue, 10 green                                                                           70       True
70  Game 71   9 red, 9 green, 4 blue; 10 red, 1 blue, 12 green; 3 blue, 13 red, 3 green                                                                               71       False
71  Game 72   2 red, 8 blue, 5 green; 2 green; 1 red, 5 green, 6 blue; 1 blue, 3 red, 12 green; 5 green, 14 blue, 1 red; 8 blue, 13 green                             72       True
72  Game 73   19 blue, 11 red, 8 green; 18 blue, 9 red, 11 green; 6 green, 19 blue, 6 red                                                                             73       False
73  Game 74   2 green, 4 red, 2 blue; 1 green, 1 red, 4 blue; 2 red, 4 green, 2 blue; 3 red, 2 blue, 6 green                                                          74       True
74  Game 75   2 blue; 1 red, 1 blue, 1 green; 1 blue; 5 blue, 2 green; 1 green, 1 red, 3 blue                                                                         75       True
75  Game 76   9 blue, 4 red, 3 green; 8 blue, 8 green, 3 red; 3 red, 2 green, 8 blue; 8 green, 6 blue, 5 red                                                          76       True
76  Game 77   7 blue, 17 green; 1 blue, 2 red, 18 green; 18 green, 1 blue, 2 red                                                                                      77       False
77  Game 78   2 red, 2 green, 1 blue; 5 green, 3 blue; 1 green, 2 blue; 2 blue, 6 red, 5 green                                                                        78       True
78  Game 79   4 red, 6 green, 17 blue; 2 blue, 3 red, 8 green; 8 red, 19 blue, 12 green; 5 red, 8 green, 12 blue; 16 blue, 1 red, 12 green; 5 green, 18 blue, 8 red   79       False
79  Game 80   1 blue, 4 red, 10 green; 6 green; 6 red, 3 green, 2 blue                                                                                                80       True
80  Game 81   2 green, 5 blue, 4 red; 3 red, 1 green, 14 blue; 3 red, 10 blue, 2 green                                                                                81       True
81  Game 82   12 red, 5 blue, 2 green; 12 blue, 6 red, 5 green; 13 blue, 1 green, 3 red; 11 red, 3 blue; 4 red, 3 green                                               82       True
82  Game 83   10 blue, 16 red, 4 green; 6 red, 2 blue, 14 green; 9 blue, 14 green; 7 blue, 1 red; 4 green, 2 red, 8 blue; 5 red, 7 green                              83       False
83  Game 84   3 red, 3 blue, 6 green; 9 red, 17 green, 16 blue; 13 blue, 7 red; 14 green, 2 red, 14 blue                                                              84       False
84  Game 85   7 blue; 8 red, 10 blue, 1 green; 6 blue, 9 red                                                                                                          85       True
85  Game 86   9 red, 6 green, 9 blue; 1 blue, 5 red; 11 red, 1 green, 11 blue; 3 green, 8 blue; 8 red, 5 green, 4 blue; 15 blue, 4 green, 2 red                       86       False
86  Game 87   2 red, 2 green; 5 red, 2 blue; 6 red                                                                                                                    87       True
87  Game 88   2 green, 5 red; 9 blue, 7 red, 3 green; 1 blue, 2 green, 3 red; 3 green, 6 blue, 1 red; 1 red, 3 green, 6 blue                                          88       True
88  Game 89   10 blue, 13 red; 15 red, 6 blue, 2 green; 2 green, 10 red, 18 blue; 1 green, 18 red, 8 blue                                                             89       False
89  Game 90   2 red, 2 blue, 9 green; 1 red, 9 green; 7 green, 3 blue, 2 red; 4 blue, 2 red, 4 green                                                                  90       True
90  Game 91   6 green, 4 red, 9 blue; 4 green, 4 red, 17 blue; 6 blue, 2 red, 4 green; 7 green, 2 red, 13 blue; 1 green, 13 blue, 1 red                               91       False
91  Game 92   4 green, 1 blue, 8 red; 7 green, 6 red; 13 red; 9 green; 6 red, 1 blue, 4 green; 2 red, 1 blue, 15 green                                                92       False
92  Game 93   8 green, 8 red, 13 blue; 4 red, 10 green; 15 blue, 11 red; 14 green, 5 red, 6 blue; 12 red, 3 blue, 13 green; 9 red, 10 green, 6 blue                   93       False
93  Game 94   14 red, 10 green; 15 red; 4 red; 4 green, 7 red, 1 blue; 6 red, 5 green; 1 red, 2 green                                                                 94       False
94  Game 95   1 blue, 11 red; 15 red, 1 blue, 3 green; 13 red, 2 blue, 3 green; 1 green, 1 blue                                                                       95       False
95  Game 96   4 red, 4 blue, 4 green; 5 blue, 5 green, 4 red; 2 red, 8 blue; 16 red, 5 green, 13 blue                                                                 96       False
96  Game 97   6 red, 13 green, 3 blue; 10 green, 4 blue; 3 red, 12 green, 4 blue; 3 red, 5 blue, 16 green; 3 red, 9 green, 1 blue                                     97       False
97  Game 98   8 red, 12 green, 2 blue; 7 green, 8 red, 1 blue; 2 blue, 6 red, 3 green; 9 red, 1 blue, 4 green                                                         98       True
98  Game 99   6 blue, 11 red, 7 green; 9 red, 6 green, 1 blue; 9 red, 2 blue                                                                                          99       True
99  Game 100  1 red, 4 blue, 2 green; 6 red, 2 green, 11 blue; 1 red, 1 blue, 2 green; 1 red, 7 blue                                                                  100      True

In [56]:
df[df.possible_sequence].game_id.sum()

2528