In [1]:
import pandas as pd
import re
import numpy as np

In [3]:
df = pd.read_csv("puzzle5.txt", header=None)
df.columns = ["coding"]
df

                                                coding
0    .......497...........................858...923...
1    436........765..............140.......+..........
2    ...*982...........=..........=....203......266...
3    .............114...588...............*...........
4    ...194.........*..............743...917.&........
..                                                 ...
135  ...502........883............/..*................
136  .............*..............893..581..534........
137  .....+....234...904.323..=..............&.894....
138  ...594............*...$.654.....+.........*......
139  ..................620............806......866....

[140 rows x 1 columns]

In [7]:
x_dim = df.coding.str.len()[0]
y_dim = len(df)
x_dim, y_dim

(140, 140)

In [12]:
symbols = np.zeros((x_dim, y_dim), dtype="int")
numbers = np.zeros((x_dim, y_dim), dtype="int")

In [17]:
import sys
np.set_printoptions(threshold=sys.maxsize)

In [22]:
def safe_access(matrix, y, x, val):
    if x < 0 or y < 0:
        return
    if x >= 140 or y >= 140:
        return
    matrix[y, x] = val

for y, row in enumerate(df.coding):
    for x, val in enumerate(row):
        if val != "." and not val.isdigit():
            symbols[y, x] = 1
            value_to_set = 1
            safe_access(symbols, y+1, x, value_to_set)
            safe_access(symbols, y, x+1, value_to_set)
            safe_access(symbols, y-1, x, value_to_set)
            safe_access(symbols, y, x-1, value_to_set)
            # giagonals
            safe_access(symbols, y-1, x-1, value_to_set)
            safe_access(symbols, y-1, x+1, value_to_set)
            safe_access(symbols, y+1, x-1, value_to_set)
            safe_access(symbols, y+1, x+1, value_to_set)
            
#symbols

In [35]:
numbers = []
for y, row in enumerate(df.coding):
    current_number = []
    found_symbol = False
    for x, val in enumerate(row):
        if val != "." and val.isdigit():
            current_number.append(val)
            if symbols[y, x] == 1:
                found_symbol = True
        else:
            if len(current_number) and found_symbol:
                a = 1
                n = 0
                for i in reversed(current_number):
                    n = n + (int(i) * a)
                    a = a * 10
                numbers.append(n) 
            current_number = []
            found_symbol = False
    if len(current_number) and found_symbol:
                a = 1
                n = 0
                for i in reversed(current_number):
                    n = n + (int(i) * a)
                    a = a * 10
                numbers.append(n) 
numbers

[858,
 801,
 487,
 436,
 140,
 859,
 982,
 203,
 263,
 375,
 402,
 691,
 575,
 114,
 588,
 631,
 952,
 14,
 661,
 706,
 333,
 194,
 743,
 917,
 375,
 544,
 664,
 807,
 452,
 969,
 309,
 873,
 941,
 828,
 197,
 427,
 728,
 566,
 13,
 243,
 80,
 329,
 470,
 145,
 111,
 659,
 259,
 569,
 130,
 385,
 123,
 199,
 640,
 463,
 978,
 920,
 266,
 380,
 83,
 323,
 870,
 466,
 453,
 297,
 588,
 786,
 390,
 886,
 728,
 852,
 606,
 863,
 396,
 538,
 287,
 301,
 133,
 33,
 537,
 466,
 793,
 218,
 721,
 986,
 222,
 701,
 437,
 3,
 626,
 68,
 419,
 806,
 976,
 875,
 174,
 488,
 790,
 487,
 532,
 13,
 503,
 11,
 734,
 978,
 19,
 622,
 712,
 68,
 619,
 863,
 596,
 160,
 659,
 757,
 437,
 520,
 304,
 568,
 974,
 255,
 318,
 183,
 675,
 849,
 161,
 687,
 710,
 854,
 441,
 891,
 476,
 235,
 434,
 880,
 673,
 683,
 800,
 120,
 707,
 74,
 562,
 988,
 487,
 685,
 251,
 146,
 142,
 398,
 769,
 238,
 848,
 662,
 773,
 895,
 591,
 233,
 611,
 186,
 429,
 304,
 468,
 960,
 810,
 534,
 645,
 313,
 239,
 509,
 720,
 844,
 939,
 508,
 401,
 649,
 158,
 200,
 409,
 982,
 46,
 517,
 303,
 647,
 660,
 530,
 704,
 69,
 879,
 589,
 131,
 871,
 672,
 611,
 415,
 283,
 569,
 21,
 842,
 109,
 157,
 719,
 679,
 664,
 664,
 668,
 203,
 14,
 427,
 833,
 484,
 434,
 796,
 65,
 479,
 126,
 382,
 121,
 836,
 789,
 624,
 350,
 544,
 6,
 882,
 848,
 625,
 88,
 382,
 971,
 5,
 622,
 914,
 627,
 641,
 373,
 912,
 651,
 162,
 557,
 901,
 503,
 337,
 357,
 552,
 816,
 240,
 636,
 993,
 934,
 961,
 43,
 324,
 888,
 370,
 170,
 805,
 517,
 639,
 389,
 929,
 408,
 94,
 9,
 605,
 571,
 512,
 591,
 976,
 895,
 489,
 751,
 240,
 931,
 464,
 608,
 94,
 486,
 172,
 121,
 909,
 583,
 128,
 929,
 24,
 762,
 230,
 422,
 285,
 434,
 390,
 921,
 261,
 949,
 382,
 903,
 595,
 833,
 973,
 268,
 506,
 251,
 25,
 234,
 306,
 281,
 36,
 918,
 432,
 406,
 344,
 700,
 610,
 839,
 33,
 610,
 537,
 20,
 402,
 926,
 768,
 93,
 161,
 74,
 298,
 519,
 925,
 586,
 264,
 85,
 371,
 822,
 540,
 447,
 987,
 305,
 379,
 707,
 670,
 397,
 842,
 552,
 464,
 666,
 844,
 515,
 114,
 393,
 800,
 647,
 696,
 203,
 418,
 19,
 462,
 786,
 691,
 756,
 165,
 596,
 32,
 280,
 259,
 398,
 425,
 796,
 1,
 305,
 451,
 332,
 706,
 327,
 841,
 74,
 791,
 419,
 927,
 148,
 459,
 998,
 783,
 444,
 959,
 106,
 366,
 385,
 846,
 907,
 585,
 447,
 441,
 7,
 142,
 944,
 634,
 587,
 930,
 935,
 819,
 29,
 3,
 35,
 415,
 980,
 58,
 74,
 922,
 175,
 233,
 645,
 620,
 429,
 951,
 616,
 524,
 799,
 551,
 602,
 920,
 503,
 654,
 395,
 451,
 263,
 897,
 370,
 409,
 970,
 661,
 48,
 475,
 839,
 497,
 446,
 533,
 794,
 432,
 167,
 486,
 500,
 459,
 540,
 110,
 569,
 785,
 455,
 815,
 452,
 365,
 929,
 978,
 709,
 84,
 427,
 466,
 608,
 796,
 680,
 142,
 603,
 621,
 635,
 302,
 296,
 679,
 801,
 290,
 464,
 980,
 627,
 850,
 108,
 513,
 656,
 739,
 715,
 354,
 245,
 629,
 995,
 41,
 45,
 840,
 506,
 148,
 995,
 541,
 914,
 950,
 53,
 28,
 275,
 138,
 812,
 665,
 101,
 308,
 691,
 482,
 292,
 307,
 661,
 135,
 932,
 992,
 54,
 191,
 931,
 400,
 649,
 504,
 88,
 581,
 743,
 140,
 642,
 891,
 309,
 695,
 361,
 603,
 170,
 643,
 24,
 291,
 538,
 461,
 725,
 23,
 279,
 713,
 449,
 434,
 785,
 991,
 946,
 830,
 136,
 439,
 24,
 519,
 289,
 408,
 579,
 708,
 650,
 370,
 13,
 887,
 688,
 673,
 218,
 927,
 722,
 124,
 427,
 312,
 922,
 307,
 706,
 16,
 934,
 608,
 459,
 761,
 647,
 641,
 242,
 5,
 715,
 122,
 262,
 928,
 728,
 610,
 502,
 222,
 40,
 923,
 540,
 701,
 291,
 351,
 141,
 878,
 820,
 988,
 204,
 889,
 119,
 797,
 395,
 671,
 322,
 101,
 257,
 733,
 544,
 600,
 862,
 421,
 582,
 484,
 565,
 695,
 384,
 592,
 904,
 629,
 717,
 93,
 726,
 961,
 535,
 715,
 439,
 630,
 615,
 912,
 777,
 602,
 567,
 3,
 107,
 914,
 3,
 2,
 763,
 885,
 185,
 182,
 383,
 60,
 459,
 117,
 504,
 358,
 480,
 990,
 33,
 834,
 33,
 494,
 181,
 66,
 492,
 176,
 857,
 376,
 315,
 954,
 982,
 763,
 329,
 179,
 245,
 61,
 352,
 509,
 952,
 423,
 131,
 17,
 191,
 33,
 306,
 144,
 503,
 491,
 298,
 415,
 426,
 526,
 669,
 498,
 698,
 447,
 575,
 142,
 617,
 890,
 212,
 730,
 519,
 971,
 384,
 18,
 219,
 537,
 677,
 587,
 120,
 334,
 700,
 944,
 636,
 848,
 743,
 388,
 109,
 540,
 40,
 596,
 155,
 324,
 820,
 520,
 443,
 621,
 276,
 910,
 276,
 376,
 739,
 368,
 428,
 434,
 878,
 932,
 207,
 959,
 289,
 196,
 172,
 688,
 25,
 944,
 725,
 110,
 148,
 426,
 483,
 771,
 932,
 800,
 947,
 457,
 931,
 834,
 721,
 477,
 491,
 114,
 191,
 213,
 909,
 194,
 633,
 792,
 605,
 633,
 108,
 611,
 719,
 696,
 865,
 724,
 950,
 320,
 260,
 121,
 338,
 719,
 180,
 516,
 649,
 643,
 941,
 160,
 140,
 94,
 39,
 789,
 135,
 532,
 90,
 608,
 515,
 743,
 194,
 993,
 669,
 259,
 948,
 262,
 695,
 623,
 473,
 602,
 83,
 679,
 259,
 447,
 363,
 105,
 957,
 659,
 299,
 599,
 898,
 464,
 606,
 237,
 768,
 416,
 228,
 2,
 557,
 517,
 859,
 855,
 877,
 427,
 468,
 535,
 500,
 117,
 726,
 381,
 428,
 43,
 472,
 476,
 517,
 951,
 249,
 920,
 859,
 825,
 393,
 15,
 770,
 16,
 278,
 417,
 626,
 23,
 954,
 868,
 502,
 373,
 254,
 246,
 530,
 982,
 179,
 635,
 538,
 362,
 180,
 278,
 138,
 922,
 543,
 12,
 92,
 150,
 994,
 788,
 220,
 301,
 593,
 597,
 500,
 603,
 928,
 966,
 536,
 768,
 800,
 64,
 924,
 203,
 423,
 451,
 453,
 638,
 314,
 896,
 459,
 186,
 581,
 846,
 188,
 624,
 400,
 268,
 664,
 12,
 943,
 733,
 597,
 388,
 149,
 468,
 698,
 143,
 426,
 878,
 875,
 871,
 929,
 504,
 245,
 94,
 651,
 915,
 40,
 440,
 236,
 511,
 994,
 753,
 459,
 212,
 18,
 964,
 71,
 768,
 827,
 567,
 2,
 781,
 827,
 437,
 813,
 317,
 102,
 333,
 285,
 304,
 622,
 953,
 377,
 997,
 320,
 877,
 636,
 42,
 772,
 419,
 189,
 17,
 366,
 563,
 228,
 153,
 839,
 218,
 449,
 409,
 69,
 652,
 576,
 255,
 397,
 469,
 568,
 374,
 499,
 477,
 137,
 319,
 207,
 808,
 933,
 737,
 367,
 807,
 219,
 436,
 226,
 266,
 215,
 769,
 41,
 922,
 271,
 350,
 346,
 662,
 175,
 979,
 215,
 652,
 39,
 61,
 154,
 426,
 335,
 487,
 194,
 42,
 790,
 750,
 253,
 617,
 717,
 908,
 489,
 953,
 316,
 ...]

In [36]:
sum(numbers)

540131